Добавил имя наставника
htmlacademy-htmlcss/1957975-sedona-33 pull request #1
Opened 2022-01-17 21:36 UTC by OzzOn1

Дмитрий Гуляев

2022-01-18 06:17 UTC, Dima-Dim requested changes

2022-01-18 06:17 UTC, Dima-Dim commented on Readme.md
> +- Наставник: `Дмитрий Гуляев`.
Отредактируй строку `Наставник` чтобы было по аналогии со строкой `Студент`. Для этого нужно добавить ссылку на мой профиль https://htmlacademy.ru/profile/dima

2022-01-18 21:49 UTC, OzzOn1 commented on Readme.md
> +- Наставник: `Дмитрий Гуляев`.
Вроде добавил, закомитил,  только не понял получилось ли сделать пулреквест или нет? Пока с интерфейсом гитхаба не разобрался.

2022-01-19 05:43 UTC, Dima-Dim commented on Readme.md
> +- Наставник: `Дмитрий Гуляев`.
Пеллриквест для изменений делать не нужно, они приходят в уже открытый.
Посмотреть их можно вот тут https://github.com/htmlacademy-htmlcss/1957975-sedona-33/pulls

2022-01-19 05:43 UTC, Dima-Dim approved these changes

2022-01-19 05:43 UTC, merged