Добавил  разметку первых двух станиц Седоны
htmlacademy-htmlcss/1957975-sedona-33 pull request #2
Opened 2022-01-24 11:50 UTC by OzzOn1

2022-01-24 16:09 UTC, Dima-Dim requested changes
"В форке вашего проекта выполните разметку главной страницы в файле index.html."

Про catalog.html ничего нет.

2022-01-24 16:09 UTC, Dima-Dim commented on catalog.html
> +                <img class="navigation_header_logo" alt="Логотип Седона" src="">
Логотип отдельный элемент, не похожий на остальные пункты меню, тем более что в меню есть пункт Главная.

2022-01-24 16:09 UTC, Dima-Dim commented on catalog.html
> +              <a class="navigation_link" href="#"> Главная</a>
Почему перед словом пробел?

2022-01-24 16:09 UTC, Dima-Dim commented on catalog.html
> +                <img class="search" alt="поиск" src="">
https://up.htmlacademy.ru/htmlcss/33/module/2/item/19 - касается всех декоративных изображений.

2022-01-24 16:09 UTC, Dima-Dim commented on catalog.html
> +            <img class="arrow" src="" alt="стрелочка">
Это не пункт списка, это декоративный разделитель.

2022-01-24 16:09 UTC, Dima-Dim commented on catalog.html
> +            <p>Гостиницы</p>
Для чего обёртка в виде p?
https://up.htmlacademy.ru/htmlcss/33/criteries#HTML-06

2022-01-24 16:09 UTC, Dima-Dim commented on catalog.html
> +            <input type="submit" value="Применить">
Не нужно использовать input type submit это не удобно, для этого есть тег button. Касается всех подобных случаев.

2022-01-24 16:09 UTC, Dima-Dim commented on catalog.html
> +            <input type="submit" value="Сбросить">
А тут вообще не submit, а reset.

2022-01-24 16:09 UTC, Dima-Dim commented on catalog.html
> +        <ul class="sorting_list">
Это набор слишком разнородных элементов, чтобы объединять их в список.

2022-01-24 16:09 UTC, Dima-Dim commented on catalog.html
> +              <li class="star_score">Рейтинг: 8,5</li>
Как то "выбивается" этот "пункт" из общего "списка".

2022-01-24 16:09 UTC, Dima-Dim commented on catalog.html
> +        </ul>
Думаю этот список должен был быть закрыт ранее.
https://up.htmlacademy.ru/htmlcss/33/module/2/item/8

2022-01-24 16:09 UTC, Dima-Dim commented on catalog.html
> +          <div class="distribution_form_buttons">
Для чего нам сейчас этот div?

2022-01-24 16:09 UTC, Dima-Dim commented on catalog.html
> +      <a class="phone_number" href="tel: +78128121212">+7(812)812-12-12</a>
Пробел лишний "tel: +78128121212".

2022-01-24 16:09 UTC, Dima-Dim commented on catalog.html
> +      <div class="footer_logo">
Тоже не понятен смысл div-а на данном этапе.

2022-01-24 16:09 UTC, Dima-Dim commented on index.html
> +        <ul class="welcome_to_sedona_list">
Почему список?

2022-01-24 16:09 UTC, Dima-Dim commented on index.html
> +            <img class="description_photo_1" src="" alt="фотография города">
Это изображение сам по себе элемент списка и ни к какому другому элементу не относится?

2022-01-24 17:09 UTC, OzzOn1 commented on catalog.html
> +                <img class="navigation_header_logo" alt="Логотип Седона" src="">
У меня в голове это просто выглядит как более удобный вариант для бедующего позиционирования элементов через css. Или в этом нет смысла? Т.к потом изображение будет одним элементом и список  ссылок вторым?

2022-01-24 17:09 UTC, OzzOn1 commented on catalog.html
> +              <a class="navigation_link" href="#"> Главная</a>
Это машинально нажимаю. буду следить за этим.

2022-01-24 17:12 UTC, OzzOn1 commented on catalog.html
> +            <img class="arrow" src="" alt="стрелочка">
Получается его можно просто удалить и потом добавить через css как картинку, типа background??
и это касается всех декор элементов?

2022-01-24 17:38 UTC, OzzOn1 commented on catalog.html
> +            <input type="submit" value="Применить">
Я вобще долго сидел с этой кнопкой и она не работала. Форма не отправлялась

2022-01-25 05:25 UTC, Dima-Dim commented on catalog.html
> +                <img class="navigation_header_logo" alt="Логотип Седона" src="">
В этом задании нет ничего про позиционирование, ведь вы его ещё не проходили. То что будет потом, будет потом, Сейчас нам нужна чистая семантичная разметка.

2022-01-25 05:26 UTC, Dima-Dim commented on catalog.html
> +            <img class="arrow" src="" alt="стрелочка">
Как это будет происходить вам обязательно покажут, а сейчас да, такое нужно удалить и это касается всех декоративных элементов.

2022-01-25 16:03 UTC, OzzOn1 commented on catalog.html
> +              <li class="star_score">Рейтинг: 8,5</li>
в это случае лучше помещать отдельно ?

2022-01-25 16:11 UTC, OzzOn1 commented on catalog.html
> +          <div class="distribution_form_buttons">
Я думал для того что бы потом в  css можно было ее задекорировать.
нельзя же повесить class на input.

**<input class="distribution_form_buttons" type="submit" value="Подписаться">**
так же нельзя сделать?

2022-01-25 16:33 UTC, OzzOn1 commented on index.html
> +        <ul class="welcome_to_sedona_list">
Там получается 3 картинки и 2 надписи идущие друг под другом в колонку, я подумал что будет проще  потом через css их позиционировать,  или их можно обернуть просто в <section> без списка? И каждый отдельный элемент завернуть в <div>?

2022-01-25 16:41 UTC, OzzOn1 commented on index.html
> +            <img class="description_photo_1" src="" alt="фотография города">
Понял это фото относится к первому элементу списка. Я подумал что они просто рядом стоят

2022-01-26 05:45 UTC, Dima-Dim commented on catalog.html
> +          <div class="distribution_form_buttons">
У вас сейчас нет ничего про декорацию. Вам ещё не рассказывали как её нужно делать. По заданию вы делаете разметку, не думаю ни о чём больше.

2022-01-26 05:46 UTC, Dima-Dim commented on index.html
> +        <ul class="welcome_to_sedona_list">
Опять же, сейчас нет никакой стилизации, делаем только минимально необходимую семантичную разметку.

2022-01-26 06:06 UTC, Dima-Dim requested changes

2022-01-26 06:06 UTC, Dima-Dim commented on catalog.html
> +        <a class="navigation_link" href="#"> <img src="" alt="ссылка логотип на главную страницу">
С первого раза не заметил что тут каких 2 изображения. Ну ладно 1, но 2 то уж точно перебор.

2022-01-26 06:06 UTC, Dima-Dim commented on catalog.html
> +            <a class="navigation_link" href="#"> Главная</a>
Всё ещё есть пробелы перед словами? Править это в 2х местах не пришлось бы, если задания отправлялись по очереди. Тоже самое касается других однотипных ошибок.

2022-01-26 06:06 UTC, Dima-Dim commented on catalog.html
> +            <input type="reset" value="Сбросить">
Это не input.

2022-01-26 06:06 UTC, Dima-Dim commented on catalog.html
> +            <input class="distribution_form_buttons" type="submit" value="Подписаться">
Это не input.

2022-01-26 06:06 UTC, Dima-Dim commented on index.html
> +        <div class="welcome_scrin">
Не нужно здесь столько контейнеров и элементов. Всё это можно сделать за пару изображений, но не сейчас. По этому сейчас это должен быть максимально простой блок.

2022-01-29 11:58 UTC, merged