Выполнил  Графику  и базовую стилизацию  для всех страниц
htmlacademy-htmlcss/1957975-sedona-33 pull request #3
Opened 2022-02-02 16:24 UTC by OzzOn1

2022-02-03 08:14 UTC, Dima-Dim commented
Почему в этом пуллриквесте появилась Базовая стилизация всех страниц? Он же для Графики и кроме графики в нём ничего быть не должно.
https://up.htmlacademy.ru/htmlcss/33/help/4.5
```Приступать к следующему заданию по тому же проекту не стоит, пока не будет принято предыдущее. Это нужно для того, чтобы не потерялся какой-то код при работе над несколькими заданиями одновременно (возможно, это будет происходить в разных ветках), а в пулреквестах не появились конфликты. Но если наставник принял задание с исправлениями, тогда можно легко переходить к новому заданию.```

2022-02-03 08:16 UTC, Dima-Dim requested changes
Оставить только графику.

2022-02-03 21:06 UTC, OzzOn1 commented
Я вроде бы удалил css но после того как  на  сайте академии нажал  обновить пулреквест. Мне сайт выдал опятьту версию со стилями.

2022-02-04 06:31 UTC, Dima-Dim requested changes
Вижу Vector-index-backgriund.svg и другие подобные названия, значит вопрос по критерию https://up.htmlacademy.ru/htmlcss/33/criteries#PROJ-03 всё ещё актуален.

2022-02-07 14:06 UTC, Dima-Dim approved these changes
images/vector-index-background.svg и images/vector_star.svg лучше использовать какой-то один подход, чтобы с этим было проще работать.

images/home-1.svg - https://up.htmlacademy.ru/htmlcss/33/criteries#PROJ-02

2022-02-07 14:06 UTC, merged