Базовая стилизация всех страниц
htmlacademy-htmlcss/1957975-sedona-33 pull request #4
Opened 2022-02-07 17:56 UTC by OzzOn1

2022-02-12 07:40 UTC, Dima-Dim requested changes

2022-02-12 07:40 UTC, Dima-Dim commented on catalog.html
> +                <img class="home" src="./images/home-1.svg" width="12" height="12" alt="ссылка на главную странцу." >
Не забудь потом убрать декоративные элементы из разметки.

2022-02-12 07:40 UTC, Dima-Dim commented on catalog.html
> +                  <li class="star"><img src="./images/vector-star.svg" width="18" height="17" alt="звезда."></li>
Всё эти изображения тоже должны уйти из разметки и без них это будет какой-то мусорный список.

2022-02-12 07:40 UTC, Dima-Dim commented on index.html
> +        <div class="page_container">
Какую необходимую стилизацию несёт это контейнер с этим классом?

2022-02-12 07:40 UTC, Dima-Dim commented on index.html
> +            <div class="vector_index_background">
`section` внутри `div` - зачем?
https://up.htmlacademy.ru/htmlcss/33/criteries#HTML-06

2022-02-12 07:40 UTC, Dima-Dim commented on styles/styles.css
> +ul{
https://up.htmlacademy.ru/htmlcss/33/criteries#CSS-02

2022-02-12 07:40 UTC, Dima-Dim commented on styles/styles.css
> +  background-color: #c0c0c0; /**временно задал цвет, чтобы было видно белый текст**/
Какой например? Не должно быть белого текста на белом фоне, если так происходит, то у этого блока должен быть свой контрастный фон, не временный.

2022-02-12 07:40 UTC, Dima-Dim commented on styles/styles.css
> +.navigation_link {
Где то есть пробел перед `{` где то нет. Делай единообразно.

2022-02-12 07:40 UTC, Dima-Dim commented on styles/styles.css
> +.vector_index_background{
Так себе название класса. Было бы нормальные, не пришлось бы писать комментарии к коду.

2022-02-12 07:40 UTC, Dima-Dim commented on styles/styles.css
> +  height: 384px;
Зафиксированная подобным образом высота при переполнении текстом приведёт к проблемам. Касается всех подобных случаев.

2022-02-12 07:40 UTC, Dima-Dim commented on styles/styles.css
> +  font: size 30px;
Если IDE не подсказывает ошибки используй https://validator.w3.org/nu/ а лучше настрой IDE, такое явно там должно "светится".

2022-02-12 22:58 UTC, OzzOn1 commented on styles/styles.css
> +  background-color: #c0c0c0; /**временно задал цвет, чтобы было видно белый текст**/
Да я почему-то решил сделать временный цвет, а не тот который нужен сразу.

2022-02-12 23:05 UTC, OzzOn1 commented on styles/styles.css
> +  height: 384px;
Я об этом подумал, но решил что в данном случае всегда одно и тоже будет. И нужно задать высоту т.к тут типизированное описание идет (цена + название) без дополнительного текста. Или всегда лучше указывать только ширину?

2022-02-13 05:10 UTC, Dima-Dim commented on styles/styles.css
> +  height: 384px;
Т.к. мы не можем спросить заказчика что тут и когда будет мы должны предусмотреть худший сценарий и в этом сценарии при увеличении количества контенат он вывалиться из блока.

2022-02-13 22:04 UTC, OzzOn1 commented on index.html
> +        <div class="page_container">
Никакую! Я может его для чего-то хотел сделать, но он не пригодился (удалил).

2022-02-13 22:11 UTC, OzzOn1 commented on styles/styles.css
> +.vector_index_background{
Что-то у меня мало идей как его назвать вобще. decorative-background ? так лучше будет?

2022-02-13 22:23 UTC, OzzOn1 commented on index.html
> +            <div class="vector_index_background">
Видимо что-то хотел сделать, но зачем не знаю.

2022-02-13 22:25 UTC, OzzOn1 commented on styles/styles.css
> +  font: size 30px;
Можешь подсказать какего  настроить, он мне показывает,  но только явныетипа  токи/запятой нету или рамку не закрыл или тег. А такого плана  не показывает (font: size 30px;)

2022-02-13 22:37 UTC, OzzOn1 commented on catalog.html
> +                  <li class="star"><img src="./images/vector-star.svg" width="18" height="17" alt="звезда."></li>
А как их убрать ? как-то через css можно добавить?

2022-02-14 06:09 UTC, Dima-Dim commented on styles/styles.css
> +  font: size 30px;
Я так понимаю у тебя VScode, по нему не подскажу, там мало что работает само из коробки, всё нужно подключать и настараивать.

2022-02-14 06:10 UTC, Dima-Dim commented on catalog.html
> +                  <li class="star"><img src="./images/vector-star.svg" width="18" height="17" alt="звезда."></li>
Вопрос ведь не в том как удалить код из файла?

2022-02-14 06:14 UTC, Dima-Dim commented on styles/styles.css
> +.vector_index_background{
А какую смысловую нагрузку он несёт? Для background не нужен отдельный класс и то что он содержит это что? Правильно, декоративное изображение, которые вы ещё не проходили. Не нужно их сейчас добавлять, вам ещё не рассказывали как это делать правильно. По этому и получаются такие странные конструкции.

2022-02-14 09:16 UTC, OzzOn1 commented on catalog.html
> +                  <li class="star"><img src="./images/vector-star.svg" width="18" height="17" alt="звезда."></li>
Не, удалить я понял через del)). Их просто пока убрать из разметки т.к мы их еще не прошли. Ты это хотел сказать? )

2022-02-14 09:34 UTC, Dima-Dim commented on catalog.html
> +                  <li class="star"><img src="./images/vector-star.svg" width="18" height="17" alt="звезда."></li>
Да, пока просто удалить из кода.

2022-02-14 09:35 UTC, OzzOn1 commented on styles/styles.css
> +ul{
Я так понял так лучше не делать потому-что он этим самым применят стили ко всему сайту. Как тогда лучше сделать что бы эти точки списка не появлялись сейчас в размете? Использовать список с классом в css или заменить вобще списки на дивы?

2022-02-14 09:39 UTC, Dima-Dim commented on styles/styles.css
> +ul{
Стилизовать через конкретные классы.

2022-02-14 10:16 UTC, OzzOn1 commented on styles/styles.css
> +  height: 384px;
А там пока получается эти блоки схлопываются в высоту до размера текста, пока так оставить?

2022-02-14 10:29 UTC, Dima-Dim commented on styles/styles.css
> +  height: 384px;
Пока можно оставить.

2022-02-14 10:46 UTC, OzzOn1 commented on catalog.html
> +                <img class="home" src="./images/home-1.svg" width="12" height="12" alt="ссылка на главную странцу." >
Про картинки маленькие забыл. Я отдельно делать не буду на них коммит. Запишу себе убрать при  следующей проверке.

2022-02-14 11:56 UTC, Dima-Dim commented on catalog.html
> +                <img class="home" src="./images/home-1.svg" width="12" height="12" alt="ссылка на главную странцу." >
Хорошо.

2022-02-15 06:32 UTC, Dima-Dim approved these changes

2022-02-15 06:32 UTC, Dima-Dim commented on index.html
> +        <section class="welcome_to_sedona">
Если заменить div-ы на section, то ещё не рашеат вопрос с семантичной вёрсткой.

2022-02-15 06:32 UTC, merged