Микросетки на флексах для всех страниц
htmlacademy-htmlcss/1957975-sedona-33 pull request #5
Opened 2022-02-19 18:38 UTC by OzzOn1

2022-02-20 09:17 UTC, Dima-Dim requested changes

2022-02-20 09:17 UTC, Dima-Dim commented on index.html
> +          <li class="socials_footer_icon"></li>
Что за пустые `li`?

2022-02-20 09:17 UTC, Dima-Dim commented on styles/styles.css
> +  list-style-type:none;
Лучше это вешать на класс, размещённый на `ul`?

2022-02-20 20:23 UTC, OzzOn1 commented on index.html
> +          <li class="socials_footer_icon"></li>
Это я не заметил, он сам закрылся, так-то он (li) ниже должен закрываться на  138 строчке. И остальные части так же.

2022-02-20 20:29 UTC, OzzOn1 commented on styles/styles.css
> +  list-style-type:none;
А почему лучше вешать на ul? Так проще контролировать эти списки? И может появится пункт списка li с другим классом?

2022-02-21 04:18 UTC, Dima-Dim commented on styles/styles.css
> +  list-style-type:none;
li с другим классом или без этого класса вполне может быть.

2022-02-21 04:19 UTC, Dima-Dim commented on index.html
> +          <li class="socials_footer_icon"></li>
Либо внимательность, либо https://validator.w3.org/nu/, а по началу лучше и то и то :)

2022-02-22 16:42 UTC, Dima-Dim approved these changes

2022-02-22 16:42 UTC, merged