Декоративные элементы на главной странице
htmlacademy-htmlcss/1957975-sedona-33 pull request #7
Opened 2022-03-11 19:17 UTC by OzzOn1

2022-03-12 17:33 UTC, Dima-Dim requested changes

2022-03-12 17:33 UTC, Dima-Dim commented on index.html
> +            <li class="navigation_item navigation_link_one">
Вместо 2-го классам можно было использовать вложенность от `navigation_main`.

2022-03-12 17:33 UTC, Dima-Dim commented on index.html
> +            <div class="vector_index_background"></div>
https://up.htmlacademy.ru/htmlcss/33/criteries#HTML-06

2022-03-12 17:33 UTC, Dima-Dim commented on index.html
> +              <img class="description_item" src="./images/icon-1.svg"  width="75" height="72" alt="иконка дома.">
https://up.htmlacademy.ru/htmlcss/33/module/2/item/19

2022-03-12 17:33 UTC, Dima-Dim commented on styles/styles.css
> +	display: block;
С отступами что-то пошло не так.

2022-03-12 17:33 UTC, Dima-Dim commented on styles/styles.css
> +  margin-top: -10px;
Не нужно без особой надобности использовать такие хаки. Когда тут нужно будет что-то подвинуть, замучаешься разбираться с тем, как это сделать и ничего не сломать.

2022-03-12 17:33 UTC, Dima-Dim commented on styles/styles.css
> + .navigation_user .navigation_item:nth-child(1) .navigation_link{
https://up.htmlacademy.ru/htmlcss/33/criteries#CSS-03

2022-03-12 17:33 UTC, Dima-Dim commented on styles/styles.css
> +  display: inline-block;
Обычно хватает flex-ов.

2022-03-12 17:33 UTC, Dima-Dim commented on styles/styles.css
> +  margin:0 240px 56px ;
Почему не просто выравнивание по центру?

2022-03-12 17:33 UTC, Dima-Dim commented on styles/styles.css
> +.light12{
Если не получается придумать нормальное название для класса, то это повод о том, что может есть какой-то более логичный и понятный вариант реализации задачи :)

2022-03-12 17:33 UTC, Dima-Dim commented on styles/styles.css
> +  border: 2px solid #000000;;
Достаточно одной `;` :)

2022-03-14 16:57 UTC, OzzOn1 commented on index.html
> +            <li class="navigation_item navigation_link_one">
Точно!!! Что-то я об этом забыл и не подумал. По сути этот калсс вобще не нужен.

2022-03-14 17:06 UTC, OzzOn1 commented on styles/styles.css
> +  margin-top: -10px;
А что  сделать тогда? просто по  макету там шапка наезжает на картинку бекграунда. а текст при этом расположен по середине. Мне в любом случае его нужно двигать в ручную.

2022-03-14 17:46 UTC, OzzOn1 commented on styles/styles.css
> + .navigation_user .navigation_item:nth-child(1) .navigation_link{
.navigation_user тут вобще можно не использовать?

2022-03-14 17:59 UTC, OzzOn1 commented on styles/styles.css
> +  display: inline-block;
То есть кнопке лучше задать ?
display: flex;
justify-content: center;
и почему лучше так сделать ?

2022-03-14 18:21 UTC, OzzOn1 commented on styles/styles.css
> +  margin:0 240px 56px ;
Я пробовал так сделать, но у меня текст не вставал по центру. Я походу понял почему. В макете у блока ширина 720px я ее установил и блок прибился к левому краю текст выравнивался в блоке который прибит в левой стороне. Я сейчас убрал ширину блока 720 и сделал просто выравнивание по центру.

2022-03-14 18:50 UTC, OzzOn1 commented on styles/styles.css
> +.light12{
Да, я это делал уже ночью... и ничего более красивого не придумал.

2022-03-14 21:30 UTC, OzzOn1 commented on index.html
> +            <div class="vector_index_background"></div>
Слушай я как то прикрутил фон поверх другого, но через  вложенность тегов.

2022-03-14 21:54 UTC, OzzOn1 commented on index.html
> +              <img class="description_item" src="./images/icon-1.svg"  width="75" height="72" alt="иконка дома.">
Посмотри, я просто добавил дивы с классами и как бекграунды дал  им эти картинки.
но у меня вопрос почему на них  не работает вырвнивание text-align и align-item?
Или эти свойства не работают на бэкграунд и их нужно ровнять через background-position?
и если это так, то как лучше тогда ровнять эти картинки через background-position или через  марджины ?

2022-03-14 22:09 UTC, OzzOn1 commented on styles/styles.css
> +	display: block;
да, пока приделывал надела новых отступов...)

2022-03-15 06:05 UTC, Dima-Dim commented on index.html
> +            <div class="vector_index_background"></div>
Это нарушает критерий и делать так не рекомендуется.

2022-03-15 06:07 UTC, Dima-Dim commented on index.html
> +              <img class="description_item" src="./images/icon-1.svg"  width="75" height="72" alt="иконка дома.">
Просто двивы с бекграндами, как я уже писал ранее, нарушают критерий https://up.htmlacademy.ru/htmlcss/33/criteries#HTML-06 думаю тебе стоит пересмотреть лайв про декоративные элементы, раз тут есть недопонимания.

2022-03-15 06:09 UTC, Dima-Dim commented on styles/styles.css
> +  margin-top: -10px;
Это вводит в заблуждение. Ты сам пишешь что "шапка наезжает на картинку" а странные свойства появляются у навигации. Потом у тебя поменяется логотип и вместе с ним тебе придётся править и навигацию тоже. А если это будешь делать не ты, то тот кто это будет делать будет очень удивлён происходящим.

2022-03-15 06:09 UTC, Dima-Dim commented on styles/styles.css
> +  display: inline-block;
Потому что это удобнее в работе, больше вариантов по выравниванию, например.

2022-03-15 06:10 UTC, Dima-Dim commented on styles/styles.css
> +  margin:0 240px 56px ;
Вам же рассказывали про центровку элементов. Не должно быть никаких проблем при задании ширины.

2022-03-15 06:12 UTC, Dima-Dim requested changes

2022-03-15 06:12 UTC, Dima-Dim commented on index.html
> +              <div class="description_item_home"></div>
https://up.htmlacademy.ru/htmlcss/33/criteries#HTML-06

2022-03-15 06:12 UTC, Dima-Dim commented on index.html
> +          <div class="welcome_to_sedona_background2">
По сути тоже нарушает https://up.htmlacademy.ru/htmlcss/33/criteries#HTML-06 потому как этот контейнер тут не нужен.

2022-03-15 11:09 UTC, OzzOn1 commented on index.html
> +              <img class="description_item" src="./images/icon-1.svg"  width="75" height="72" alt="иконка дома.">
я просто посмотрел еще раз фоны знакомство 13 пункт, https://up.htmlacademy.ru/profession/frontender/13/htmlcss/33/module/7/item/4/13

2022-03-15 11:13 UTC, OzzOn1 commented on index.html
> +              <img class="description_item" src="./images/icon-1.svg"  width="75" height="72" alt="иконка дома.">
Всё, я понял что не так было.

2022-03-16 06:17 UTC, Dima-Dim commented on styles/styles.css
> +  height: 60px;
Приведёт к проблемам при переполнении.

2022-03-16 06:17 UTC, Dima-Dim commented on styles/styles.css
> +  height: auto;
Это значения по умолчанию, их не обязательно указывать явно.

2022-03-16 06:17 UTC, merged