Декоративные элементы на внутренней странице
htmlacademy-htmlcss/1957975-sedona-33 pull request #8
Opened 2022-03-16 17:50 UTC by OzzOn1

2022-03-17 07:13 UTC, Dima-Dim requested changes

2022-03-17 07:13 UTC, Dima-Dim commented on catalog.html
> +                <svg aria-hidden="true" focusable="false" width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M6 .3 0 5.8V12h12V5.8L6 .3ZM11 11H1V6.2l5-
Для чего оно в разметке?

2022-03-17 07:13 UTC, Dima-Dim commented on catalog.html
> +              <svg class="image_vector" aria-hidden="true" focusable="false" width="5" height="8" viewBox="0 0 5 8" fill="none" xmlns="http://www.w3.org/2000/svg"><g opacity=".3" clip-path="url(#a)">
Тоже непонятно для чего этонести в разметку.

2022-03-17 07:13 UTC, Dima-Dim commented on catalog.html
> +              <svg width="16" height="14" viewBox="0 0 16 14" fill="none" aria-hidden="true" focusable="false" xmlns="http://www.w3.org/2000/svg">
По всем svg в разметке подумать зачем оно тут и почему нельзя его использоватье иначе.

2022-03-17 07:13 UTC, Dima-Dim commented on catalog.html
> +          <span class="distribution_text_inner">Только полезная информация и никакого спама,<br> честное бойскаутское!</span>
Почему сменил p на span?

2022-03-17 10:47 UTC, OzzOn1 commented on catalog.html
> +          <span class="distribution_text_inner">Только полезная информация и никакого спама,<br> честное бойскаутское!</span>
Четно не знаю, видимо просто что-то пытался сделать.

2022-03-17 11:12 UTC, OzzOn1 commented on catalog.html
> +                <svg aria-hidden="true" focusable="false" width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M6 .3 0 5.8V12h12V5.8L6 .3ZM11 11H1V6.2l5-
Всё я понял. В разметку вставляем svg которые могут менять состояния. А в css те которые  просто декор. Но именно эта картинка служит ссылкой на первую страницу и чисто теоретически ей можно  задать другие состояния. Я бы её так и оставил. А вот что, костально следующей картинки(стрелки -указателя), ее - да я перенесу в css как фон.

2022-03-17 12:15 UTC, Dima-Dim commented on catalog.html
> +                <svg aria-hidden="true" focusable="false" width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M6 .3 0 5.8V12h12V5.8L6 .3ZM11 11H1V6.2l5-
Если у неё прямо сейчас нет состояний, то быть её тут не должно.

2022-03-17 13:24 UTC, OzzOn1 commented on catalog.html
> +                <svg aria-hidden="true" focusable="false" width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M6 .3 0 5.8V12h12V5.8L6 .3ZM11 11H1V6.2l5-
Я так и не пони зачем вставлять такие мелкие иконки через бакграунд. Их очень сложно двигать и позиционировать на странице. Я по сути 2 часа сижу и двигаю их туда сюда. Сможешь сейчас посмотреть сразу так я это делаю или нет. Потому что я вобще не знаю как тогда двигать  картинки со зведами. и как вставлять 4 одинаковые картинки в одну точку и раздвигать их.

2022-03-17 13:32 UTC, Dima-Dim commented on catalog.html
> +                <svg aria-hidden="true" focusable="false" width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M6 .3 0 5.8V12h12V5.8L6 .3ZM11 11H1V6.2l5-
У вас был целый лайв про декоративные элементы в котором рассказывали как их размещать. Такое ощущение что ты прошёл его мимо. И да, вёрстка это, в том числе про позиционирование элементом, в соответствие с макетом, попадая в пиксели.

2022-03-17 13:43 UTC, OzzOn1 commented on catalog.html
> +                <svg aria-hidden="true" focusable="false" width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M6 .3 0 5.8V12h12V5.8L6 .3ZM11 11H1V6.2l5-
Да, я его вот и пересматриваю сейчас. Просто сразу не все понятно и не все запоминается. я просто думал что сидеть и двигать эту картинку в ручную условно не самое хорошее решение. А если задать ей сразу првильные размеры и разместить в блоке, то она встанет сразу куда надо.

2022-03-18 06:21 UTC, Dima-Dim commented on styles/styles.css
> +.stars_rating_amara{
Уже лучше, но колличество звёзд лучше привязывать не к конкретному отелю. Ведь звёзд у этого отеля может стать и больше и меньше.

2022-03-18 06:21 UTC, merged